[package]
name = "car_test_1"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14", features = ["dynamic_linking"] }
bevy_rapier3d = { version = "0.27", features = ["debug-render-3d"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3